title: "Sara Golestani"
baseurl: ""

first-name: 'Sara'
last-name: 'Naseri Golestani'
job-title: 'Recent Graduate Machine Learning Engineer with more than 5 years of experience in this field'
profpic: '/resources/img/profilepic.jpg'
profpic-retina: '/resources/img/profilepic@2x.jpg'
LinkedIn: 's-golestani'
email: 'sarah.gln.97@gmail.com'
github: 'sarangolestani'
location: 'Calgary, AB, Canada'
location-url: "https://goo.gl/maps/tTXYvHFQ9rj6GyiLA"

# For syntax highlighting, the primary programming langauge you intend to use in
# blog articles. By default, Google's prettify will be used for this programming
# language, as per the instructions here: https://github.com/google/code-prettify
# For example, if I indicate `scala`, all pre/code blocks will have the `lang-scala`
# class added to the markup, triggering prettify to highlight the syntax as Scala.
primarylanguage: Python
# To sidestep the default language for syntax highlighting set here, you can be
# explicit in your blog articles with the langauge you'd prefer to use. E.g.,
# <pre>
#   <code class="prettyprint lang-ruby">
#    ..ruby code here...
#   </code>
# </pre>

# categories:
#   blog:
#     permalink: /blog/:title.html

# Settings for blog RSS feed
name: "Sara Golestani"
description: "Hello! I am Sara, a proud alumni of the University of Calgary and a Machine Learning Developer. Proficient in designing, training, and deploying machine learning models, including neural networks and deep learning architectures, for diverse applications such as object detection, natural language processing (NLP), and resource usage forecasting. Adept at creating efficient data processing pipelines for complex datasets, including 3D point cloud data, and extracting meaningful features for machine learning tasks. Hands-on experience in developing end-to-end ML pipelines, from data preprocessing to model deployment, utilizing Azure and Docker for scalability and efficiency. "
url: "https://sarangolestani.github.io"
tagline: "Sara Naseri Golestani Page, Machine Learning Engineer, Data Scientist"

permalink: /:categories/:title.html
# markdown: redcarpet
highlighter: null

sass:
  style: compressed

livereload: true

plugins:
  - jekyll-seo-tag


social:
  name: Sara Naseri Golestani
  links:
    - https://www.linkedin.com/in/s-golestani/
    - https://github.com/sarangln
